Nano blade rewrite
Slimefun-Addon-Community/LiteXpansion pull request #22
Opened 2021-01-22 21:13 UTC by WalshyDev

## Short Description
Rewriting the way the nano blade works to be more inline with Tekkit/FTB.

## Additions/Changes/Removals
* Nano blade now does 20 base damage while on and 4 while off
* It utilises PDC
* Optimised in parts
* Energy now depletes while it is on rather than on hit

## Related Issues

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-01-23 09:04 UTC, J3fftw1 commented
When you are working on it anyways mind fixing the electric chestplate aswell

2021-02-15 12:42 UTC, J3fftw1 requested changes

2021-02-15 12:42 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/Items.java
> +        "&c&o&8\u21E8 &e\u26A1 &70 / 100 J"
Food_synth.capacity?

2021-02-15 12:42 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/weapons/NanoBlade.java
> +                new ItemStack(Material.GLOWSTONE_DUST), Items.ADVANCED_ALLOY, null,
Is this the official recipe?

2021-02-15 13:03 UTC, J3fftw1 requested changes

2021-02-15 13:03 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/items/PassiveElectricRemoval.java
> +//            final float charge = ChargeUtils.getCharge(meta);
Remove comment

2021-02-15 13:03 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/items/PassiveElectricRemoval.java
> +//            ChargeUtils.setCharge(meta, newCharge, CAPACITY);
Remove comment

2021-02-15 13:38 UTC, J3fftw1 commented
Also on top of the current requested changes if you dont mind can you remove cscorelib dependency and update bstats dependency

2021-02-15 13:41 UTC, WalshyDev commented on src/main/java/dev/j3fftw/litexpansion/items/PassiveElectricRemoval.java
> +//            final float charge = ChargeUtils.getCharge(meta);
These are for the next RC

2021-02-15 13:42 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/items/PassiveElectricRemoval.java
> +//            final float charge = ChargeUtils.getCharge(meta);
Ah okay ignore my comment then

2021-02-15 13:45 UTC, WalshyDev commented on src/main/java/dev/j3fftw/litexpansion/Items.java
> +        "&c&o&8\u21E8 &e\u26A1 &70 / 100 J"
Not related

2021-02-15 13:47 UTC, WalshyDev commented on src/main/java/dev/j3fftw/litexpansion/weapons/NanoBlade.java
> +                new ItemStack(Material.GLOWSTONE_DUST), Items.ADVANCED_ALLOY, null,
Yes - https://tekkitclassic.fandom.com/wiki/Nano_Saber

2021-02-15 13:52 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/litexpansion/weapons/NanoBlade.java
> +                new ItemStack(Material.GLOWSTONE_DUST), Items.ADVANCED_ALLOY, null,
okay good

2021-02-15 13:52 UTC, J3fftw1 commented
> Also on top of the current requested changes if you dont mind can you remove cscorelib dependency and update bstats dependency

If you dont mind doing this then its ready for merge

2021-02-15 14:01 UTC, WalshyDev commented
Alright, it's good to go

2021-02-15 14:12 UTC, J3fftw1 approved these changes
Lgtm

2021-02-15 14:14 UTC, merged